blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogList, name="blog-list"),
    path('category/<str:meta_title>/', views.category_detail, name="category_detail"),
    path('<str:meta_title>', views.blogDetail, name="blog-detail"),

]

store/urls.py
from django.urls import path, include
from store import views

app_name = "store"



urlpatterns = [
    path("", views.index, name="home"),
    path("offer/", views.offer, name="offer"),
    path("category/", views.category_list, name="category"),
    path("shop/", views.shop, name="shop"),
    path("category/<str:meta_title>", views.category_shop, name="category-shop"),
    path("brand/<str:meta_title>", views.brand_shop, name="brand-shop"),
    path("hot_deals/", views.hot_deals, name="hot_deals"),
    path("search/", views.search_list, name="search"),
    path("my-cart/", views.cart_view, name="cart-view"),
    path("category/<cid>/", views.category_detail, name="category_detail"),
    path("shipping_address/", views.shipping_address, name="shipping_address"),
    path("checkout/<oid>/", views.checkout_view, name="checkout"),
    path("custom-checkout/<oid>/", views.custom_checkout_view, name="checkout2"),
    path('checkout/order-detail/<id>/', views.PaymentConfirmation.as_view(), name='order-detail'),
    path('success-payment/', views.PaymentSuccessView, name='success'),
    path('failed-payment/', views.PaymentFailedView, name='failed'),    
    
    path("payment-completed/<oid>/", views.payment_completed_view, name="payment-completed"),


    # Ajax URLs
    path("ajax/add-to-cart/", views.add_to_cart, name="add-to-cart"),
    path("ajax/helpful-review/", views.helpful_review, name="helpful-review"),
    path("ajax/add-review/<int:pid>/", views.add_review, name="add-review"),
    path("ajax/ask-question/", views.ask_question, name="ask-question"),
    path('ajax/update-cart/',views.update_cart,name='update-cart'),
    path('ajax/delete-from-cart/',views.delete_item_from_cart,name='delete-from-cart'),

    # API URLs
    path('api/checkout-session/<id>/', views.create_checkout_session, name='api_checkout_session'),
    path('country_get/', views.country_get, name='country_get'),


    path('webhook/', views.webhook, name='webhook'),



    path('get-subcategories/<str:category_meta_title>', views.get_subcategories, name='get-subcategories'),
    path('nav-search/', views.nav_search, name='nav-search'),
    path("<str:meta_title>/", views.product_detail, name="product-detail"),

]

tokyostore/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from store.views import pageNotFoundView
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from store.models import Product, Brand, Category
from blog.models import Post
from store.views import pageNotFoundView

blog_info_dict = {
    "queryset": Post.objects.all(),
    "date_field": "date",
}

store_info_dict = {
    "queryset": Product.objects.all(),
    "date_field": "date",
}

urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('khalabiza/', admin.site.urls),
    
    path('user/', include("userauths.urls")),
    path('', include("core.urls")),
    path('vendor/', include("vendor.urls")),
    path('', include("addons.urls")),
    path('report/', include("reports.urls")),
    path('blog/', include("blog.urls")),
    path('help-center/', include("help_center.urls")),

    
    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    
    
    # Re-Captcha Validation
    # path('captcha/', include('captcha.urls')),
    
    # Password Reset
    path('user/password-reset/', auth_views.PasswordResetView.as_view( template_name='userauths/password-reset/password_reset.html', subject_template_name='userauths/password-reset/password_reset_subject.txt', email_template_name='userauths/password-reset/password_reset_email.html', success_url='/user/check_email/' ), name='password_reset'),
    path('user/password-reset/done/', auth_views.PasswordResetDoneView.as_view( template_name='userauths/password-reset/password_reset_done.html' ), name='password_reset_done'),
    path('user/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( template_name='userauths/password-reset/password_reset_confirm.html' ), name='password_reset_confirm'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),

    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),),
    
     path("sitemap.xml", sitemap, {"sitemaps": {"blog": GenericSitemap(blog_info_dict), "store": GenericSitemap(store_info_dict)}}),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +[path('404/', pageNotFoundView, name="404"),] + [path('', include("store.urls"))] + [path('<path:invalid_path>/', pageNotFoundView),]
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +[path('404/', pageNotFoundView, name="404"),] + [path('', include("store.urls"))] + [path('<path:invalid_path>/', pageNotFoundView),]
    

userauths/urls.py
from django.urls import path
from userauths import views
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500


app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.Register, name="sign-up"),
    path("sign-in/", views.loginViewTemp, name="sign-in"),
    path("sign-in-2/", views.loginView, name="sign-in-2"),
    path("sign-out/", views.logoutView, name="sign-out"),
    path("vendor_sign_in/", views.loginAsVendor, name="vendor_sign_in"),
    path("check_email/", views.check_email, name="check_email"),
    
    
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 
from django.db.models.signals import post_save
from django.utils.html import mark_safe
from django_ckeditor_5.fields import CKEditor5Field
import logging


from PIL import Image
from shortuuid.django_fields import ShortUUIDField

IDENTITY_TYPE = (
    ("national_id_card", "National ID Card"),
    ("drivers_licence", "Drives Licence"),
    ("international_passport", "International Passport")
)

GENDER = (
    ("F", "Female"),
    ("M", "Male"),
)


def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (instance.user.id, ext)
    return 'user_{0}/{1}'.format(instance.user.id,  filename)

class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100, null=True, blank=True)
    full_name = models.CharField(max_length=100, null=True, blank=True)
    gz_coins = models.IntegerField(default=0, null=True, blank=True)
    bio = models.CharField(max_length=100, null=True, blank=True)
    roles = models.CharField(max_length=100, null=True, blank=True)
    total_spent = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    billing_first_name = models.CharField(max_length=500, null=True, blank=True)
    billing_last_name = models.CharField(max_length=500, null=True, blank=True)
    billing_email = models.CharField(max_length=500, null=True, blank=True)
    billing_phone = models.CharField(max_length=500, null=True, blank=True)
    billing_address = models.CharField(max_length=500, null=True, blank=True)
    billing_state = models.CharField(max_length=500, null=True, blank=True)
    billing_country = models.CharField(max_length=500, null=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        if self.pk:  # Check if the object is already in the database (updating)
            original = User.objects.get(pk=self.pk)
            if self.gz_coins != original.gz_coins:
                print(f"gz_coins changed from {original.gz_coins} to {self.gz_coins} for user {self.username}")
        
        super(User, self).save(*args, **kwargs)
    # def save(self, *args, **kwargs):
    #     if self.roles == "wcfm_vendor":
    #         "vendor.Vendor".objects.create(user=self, profile=None)
    #     else:
    #         self.product.status = "published"
    #         self.product.save()
            
    #     super(User, self).save(*args, **kwargs) 



class Profile(models.Model):
    pid = ShortUUIDField(length=7, max_length=25, alphabet="abcdefghijklmnopqrstuvxyz123")
    cover_image = models.ImageField(upload_to=user_directory_path, default="cover.jpg", blank=True, null=True)
    image = models.ImageField(upload_to=user_directory_path, default="default.jpg", null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    full_name = models.CharField(max_length=1000, null=True, blank=True)
    bio = models.CharField(max_length=100, null=True, blank=True)
    about_me = models.TextField(null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, choices=GENDER, null=True, blank=True)


    country = models.ForeignKey("addons.TaxRate", on_delete=models.SET_NULL, null=True, related_name="user_country_tax", blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=1000, null=True, blank=True)
    postal_code = models.CharField(max_length=1000, null=True, blank=True)
    
    identity_type = models.CharField(choices=IDENTITY_TYPE, default="national_id_card", max_length=100, null=True, blank=True)
    identity_image = models.ImageField(upload_to=user_directory_path, default="id.jpg", null=True, blank=True)

    facebook = models.URLField(default="https://facebook.com/", null=True, blank=True)
    instagram = models.URLField(default="https://instagram.com/", null=True, blank=True)
    twitter = models.URLField(default="https://twitter.com/", null=True, blank=True)
    whatsApp = models.CharField(default="+123 (456) 789", max_length=100, blank=True, null=True)

    verified = models.BooleanField(default=False)
    seller = models.BooleanField(default=False)
    subscribed_newsletter = models.BooleanField(default=False)

    referral_earning = models.DecimalField(default=0.00, decimal_places=2, max_digits=12)
    wallet = models.DecimalField(default=0.00, decimal_places=2, max_digits=12)

    account_number = ShortUUIDField(length=10, max_length=25, alphabet="1234567890")
    pin = ShortUUIDField(length=4, max_length=6, alphabet="1234567890")
    code = models.CharField(max_length=12, blank=True, null=True)
    recommended_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='ref_by')
    
    saved_product = models.ManyToManyField("store.Product",blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        if self.full_name:
            return f"{self.full_name}"
        else:
            return f"{self.user.username}"


    # def save(self, *args, **kwargs):
    #     img = Image.open(self.image.path)
    #     if img.height > 700 or img.width > 700:
    #         output_size = (700, 700)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)
    #     super().save(*args, **kwargs)

    
    def profile_image(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" object-fit:"cover" />' % (self.image))

    
    
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()


post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)






# class User(AbstractUser):
#     email = models.EmailField(null=True, blank=True)
#     username = models.CharField(max_length=100, null=True, blank=True)
#     full_name = models.CharField(max_length=100, null=True, blank=True, unique=True)
#     bio = models.CharField(max_length=100, null=True, blank=True)
#     roles = models.CharField(max_length=100, null=True, blank=True)
#     total_spent = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
#     billing_first_name = models.CharField(max_length=500, null=True, blank=True)
#     billing_last_name = models.CharField(max_length=500, null=True, blank=True)
#     billing_email = models.CharField(max_length=500, null=True, blank=True)
#     billing_phone = models.CharField(max_length=500, null=True, blank=True)
#     billing_address = models.CharField(max_length=500, null=True, blank=True)
#     billing_state = models.CharField(max_length=500, null=True, blank=True)
#     billing_country = models.CharField(max_length=500, null=True, blank=True)

#     USERNAME_FIELD = "full_name"
#     REQUIRED_FIELDS = ['username']

#     def __str__(self):
#         return self.username

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User, Profile
from django.forms import ImageField, FileInput
from django.contrib.auth import get_user_model
# from captcha.fields import CaptchaField


class DateInput(forms.DateInput):
    input_type = "date"

class StaffCreationForm(forms.ModelForm):
    
    class Meta:
        model = get_user_model()
        fields = "__all__"
        widgets = {
            'date_joined': DateInput(),
            'last_login': DateInput(),
        }

class UserRegisterForm(UserCreationForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':'Full Name'}), max_length=100, required=True)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':'Username'}), max_length=100, required=True)
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control' , 'id': "", 'placeholder':'Email Address'}), required=True)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'btn__btn__btn form-control' , 'id': "", 'placeholder':'Password'}), required=True)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={ 'class': 'btn__btn__btn form-control' , 'id': "", 'placeholder':'Confirm Password'}), required=True)
    # captcha=CaptchaField()
    
    class Meta:
        model = User
        fields = ['full_name', 'username', 'email', 'password1', 'password2']
       
GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
)

class ProfileUpdateForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter Full Name', 'class': 'form-control', 'id': ""}), max_length=1000, required=False)
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Residential Address', 'class': 'form-control', 'id': ""}), max_length=1000, required=False)
    city = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'City', 'class': 'form-control', 'id': ""}), max_length=1000, required=False)
    state = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'State', 'class': 'form-control', 'id': ""}), max_length=1000, required=False)
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.Select(attrs={'class': 'form-control', 'id': ""}), required=False)
    phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Mobile Number', 'class': 'form-control', 'id': ""}), max_length=1000, required=False)
    image = ImageField(widget=FileInput)
    
    class Meta:
        model = Profile
        fields = ['full_name', 'image' ,'gender','address', 'city' , 'state', 'country' , 'phone' ]
        widgets = {
            'image': FileInput(attrs={'id': 'loadFile(event)'}),
            'identity_image': FileInput(attrs={'id': 'preview_id()'}),
        }

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Enter Email', 'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['email']

templates/userauths/password-reset/change-password.html
{% extends "partials/base-tk.html" %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
<!-- {% crispy form %} -->
<style>
    #id_email{
        border: 1px solid black;
        width: 100%;
        height: 50px;
        border-radius: 10px;
        font-family: poppins;
    }
    #id_email:active{
        outline: none;
    }
    #id_email:focus{
        outline: none;
    }
</style>



<section class="our-log-reg bgc-f5">
    <div class="container">
        <div class="row">
    <div class="col-lg-6 col-xl-5 col-xxl-4 m-auto">
        
        {% if form.errors %}
            
            
        <div class="alert alert-danger">
            <strong>{{form.errors}}</strong>
        </div>
        {% endif %}

      <div class="log_reg_form mt70-992">
        <h2 class="title">Changer le mot de passe</h2>
        <div class="login_form">
          <form method="POST">
            {% csrf_token %}
            <div class="mb-2 mr-sm-2">
              <label class="form-label">Nouveau mot de passe</label>
              <br>
              {{form}}
            </div>
            <button type="submit" class="btn btn-lofg btn-tfhm purple-btn mt20 w100">Enregistrer le nouveau mot de passe</button>
          </form>
        </div>
      </div>
    </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/userauths/password-reset/check_email.html
{% extends "partials/base-tk.html" %}
{% load static %}
{% block content %}

<style>
    #id_email{
        border: 1px solid black;
        width: 100%;
        height: 50px;
        border-radius: 10px;
        font-family: poppins;
    }
    #id_email:active{
        outline: none;
    }
    #id_email:focus{
        outline: none;
    }
</style>

<section class="our-log-reg bgc-f5">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-xl-5 col-xxl-4 m-auto">
                <div class="log_reg_form mt70-992">
                    <h2 class="title">Email envoyé <i class="fas fa-check-circle"></i></h2>
                    <div class="login_form">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="mb-2 mr-sm-2">
                                <label class="form-label">Vérifiez votre adresse e-mail et suivez les instructions pour réinitialiser votre mot de passe</label>
                            </div>
                            <a href="{% url 'store:home' %}" class="btn btn-lofg btn-tfhm purple-btn mt20 w100">Accueil</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/userauths/password-reset/password_reset.html
{% extends "partials/base-tk.html" %}
{% load static %}
{% block content %}

<style>
    #id_email{
        border: 1px solid black;
        width: 100%;
        height: 50px;
        border-radius: 10px;
        font-family: poppins;
    }
    #id_email:active{
        outline: none;
    }
    #id_email:focus{
        outline: none;
    }
</style>

<section class="our-log-reg bgc-f5">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-xl-5 col-xxl-4 m-auto">
                <div class="log_reg_form mt70-992">
                    <h2 class="title">Réinitialisation du mot de passe</h2>
                    <div class="login_form">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="mb-2 mr-sm-2">
                                <label class="form-label">Adresse e-mail</label>
                                <br>
                                {{form.email}}
                            </div>
                            <button type="submit" class="btn btn-lofg btn-tfhm purple-btn mt20 w100">Réinitialiser le mot de passe</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/userauths/password-reset/password_reset_complete.html
{% extends "partials/base-tk.html" %}
{% load static %}
{% block content %}

<style>
    #id_email{
        border: 1px solid black;
        width: 100%;
        height: 50px;
        border-radius: 10px;
        font-family: poppins;
    }
    #id_email:active{
        outline: none;
    }
    #id_email:focus{
        outline: none;
    }
</style>

<section class="our-log-reg bgc-f5">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-xl-5 col-xxl-4 m-auto">
                <div class="log_reg_form mt70-992">
                    <h3 class="title">Réinitialisation du mot de passe réussie. <i class="fas fa-check-circle"></i></h3>
                    <div class="login_form">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="mb-2 mr-sm-2">
                                <label class="form-label">Félicitations, votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter.</label>
                            </div>
                            <a href="{% url 'userauths:sign-in' %}" class="btn btn-lofg btn-tfhm purple-btn mt20 w100">Connexion</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/userauths/password-reset/password_reset_confirm.html
{% extends "partials/base-tk.html" %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
<!-- {% crispy form %} -->
<style>
    #id_email{
        border: 1px solid black;
        width: 100%;
        height: 50px;
        border-radius: 10px;
        font-family: poppins;
    }
    #id_email:active{
        outline: none;
    }
    #id_email:focus{
        outline: none;
    }
</style>

<section class="our-log-reg bgc-f5">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-xl-5 col-xxl-4 m-auto">
                <div class="log_reg_form mt70-992">
                    <h2 class="title">Réinitialisation du mot de passe</h2>
                    <div class="login_form">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="mb-2 mr-sm-2">
                                <label class="form-label">Nouveau mot de passe</label>
                                <br>
                                {{form}}
                            </div>
                            <button type="submit" class="btn btn-lofg btn-tfhm purple-btn mt20 w100">Réinitialiser le mot de passe</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/userauths/password-reset/password_reset_done.html
{% extends 'partials/base.html' %}
{% load static %}
{% block title %}
  Réinitialisation du mot de passe effectuée
{% endblock title %}
{% load humanize %}
{% block content %}


    <!-- Section de la bannière -->
    <section class="banner-section inner-banner contact">
        <div class="overlay">
            <div class="shape-area">
                <img src="{% static 'assets/images/contact-illus.png' %}" class="contact-illu" alt="image">
            </div>
            <div class="banner-content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-9 col-md-10">
                            <div class="main-content">
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Fin de la section de la bannière -->

    <!-- Section de contact -->
    <section class="contact-section">
        <div class="overlay">
            <div class="container bg-area">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <div class="section-header text-center">
                            <h2 class="title">Email envoyé</h2>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="form-content">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="row justify-content-center">
                                    <div class="col-md-12">
                                        <div class="single-input">
                                            <p class="text-center">Un email avec des instructions de réinitialisation de mot de passe a été envoyé à votre adresse email fournie.</p>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Fin de la section de contact -->
  
            <!-- Fin de l'enregistrement -->
{% endblock content %}

templates/userauths/password-reset/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}Bonjour, Vous recevez cet e-mail parce que vous avez demandé une réinitialisation de mot de passe pour votre compte utilisateur sur {{ site_name }}.{% endblocktrans %}

{% trans "Veuillez vous rendre sur la page suivante et choisir un nouveau mot de passe :" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Votre nom d'utilisateur, au cas où vous l'auriez oublié :" %} {{ user.get_username }}

{% trans "Merci d'utiliser notre site !" %}

{% blocktrans %}L'équipe de {{ site_name }}{% endblocktrans %}

{% endautoescape %}