blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogList, name="blog-list"),
    path('category/<str:meta_title>/', views.category_detail, name="category_detail"),
    path('<str:meta_title>', views.blogDetail, name="blog-detail"),

]

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    #path("my-dashboard/", views.buyer_account, name="buyer-dashboard"),
    path("profile/", views.buyer_profile, name="profile"),
    path("settings/", views.buyer_profile_settings, name="settings"),
    path("my-orders/", views.buyer_orders, name="buyer-orders"),
    path("my-orders/<oid>/", views.buyer_order_detail, name="buyer-order-detail"),

    # Shipping Address
    path("my-address/", views.buyer_address, name="buyer-address"),
    path("my-address/edit/<id>/", views.buyer_edit_address, name="buyer-edit-address"),
    path("my-address/delete/<id>/", views.buyer_delete_address, name="buyer-delete-address"),

    # Billing Address
    path("my-billing-address/", views.buyer_billing_address, name="buyer-billing-address"),
    path("my-billing-address/edit/<id>/", views.buyer_edit_billing_address, name="buyer-edit-billing-address"),
    path("add_billing_address", views.add_billing_address, name="add_billing_address"),
    path("my-billing-address/delete/<id>/", views.buyer_delete_billing_address, name="buyer_delete_billing_address"),

    path("my-wishlist/", views.buyer_wishlist, name="buyer-wishlist"),
    path("my-invoices/", views.buyer_invoices, name="buyer-invoices"),
    path("my-invoice/<oid>/", views.buyer_invoice_detail, name="buyer-invoice-detail"),
    path("my-bids/", views.buyer_bids, name="buyer_bids"),
    path("my-bids-detail/<pid>/<bid>", views.buyer_bids_detail, name="buyer_bids_detail"),
    path("order-tracker/", views.buyer_track_order, name="order-tracker"),
    path("tracked-order/<oid>/", views.tracked_order, name="tracked-order"),
    path("buyer_offer", views.buyer_offer, name="buyer_offer"),
    path("buyer_offer_detail/<pid>/<oid>/", views.buyer_offer_detail, name="buyer_offer_detail"),
    path("cancel_order/<oid>/", views.cancel_order, name="cancel_order"),
    path("cancel_orderitem/", views.cancel_orderitem, name="cancel_orderitem"),

    # Messaging
    path('inbox/', views.inbox, name="buyer_message"),
    path('inbox/<username>/', views.get_inbox, name="inbox-detail"),
    path('send_message_ajax/<username>/', views.send_message_ajax, name="send_message_ajax"),
    path('search_user/', views.search_users, name="search_users"),

    # Ajax
    path("delete-wishlist/<id>/", views.delete_from_wishlist, name="delete-wishlist"),
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),
    path("make-default-address/", views.make_address_default, name="make-default-address"),
    path("make-billing-default-address/", views.make_billing_address_default, name="make-default-billing-address"),

]

store/urls.py
from django.urls import path, include
from store import views

app_name = "store"



urlpatterns = [
    path("", views.index, name="home"),
    path("offer/", views.offer, name="offer"),
    path("category/", views.category_list, name="category"),
    path("shop/", views.shop, name="shop"),
    path("category/<str:meta_title>", views.category_shop, name="category-shop"),
    path("brand/<str:meta_title>", views.brand_shop, name="brand-shop"),
    path("hot_deals/", views.hot_deals, name="hot_deals"),
    path("search/", views.search_list, name="search"),
    path("my-cart/", views.cart_view, name="cart-view"),
    path("category/<cid>/", views.category_detail, name="category_detail"),
    path("shipping_address/", views.shipping_address, name="shipping_address"),
    path("checkout/<oid>/", views.checkout_view, name="checkout"),
    path("custom-checkout/<oid>/", views.custom_checkout_view, name="checkout2"),
    path('checkout/order-detail/<id>/', views.PaymentConfirmation.as_view(), name='order-detail'),
    path('success-payment/', views.PaymentSuccessView, name='success'),
    path('failed-payment/', views.PaymentFailedView, name='failed'),    
    
    path("payment-completed/<oid>/", views.payment_completed_view, name="payment-completed"),


    # Ajax URLs
    path("ajax/add-to-cart/", views.add_to_cart, name="add-to-cart"),
    path("ajax/helpful-review/", views.helpful_review, name="helpful-review"),
    path("ajax/add-review/<int:pid>/", views.add_review, name="add-review"),
    path("ajax/ask-question/", views.ask_question, name="ask-question"),
    path('ajax/update-cart/',views.update_cart,name='update-cart'),
    path('ajax/delete-from-cart/',views.delete_item_from_cart,name='delete-from-cart'),

    # API URLs
    path('api/checkout-session/<id>/', views.create_checkout_session, name='api_checkout_session'),
    path('country_get/', views.country_get, name='country_get'),


    path('webhook/', views.webhook, name='webhook'),



    path('get-subcategories/<str:category_meta_title>', views.get_subcategories, name='get-subcategories'),
    path('nav-search/', views.nav_search, name='nav-search'),
    path("<str:meta_title>/", views.product_detail, name="product-detail"),

]

tokyostore/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from store.views import pageNotFoundView
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from store.models import Product, Brand, Category
from blog.models import Post
from store.views import pageNotFoundView

blog_info_dict = {
    "queryset": Post.objects.all(),
    "date_field": "date",
}

store_info_dict = {
    "queryset": Product.objects.all(),
    "date_field": "date",
}

urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('khalabiza/', admin.site.urls),
    
    path('user/', include("userauths.urls")),
    path('', include("core.urls")),
    path('vendor/', include("vendor.urls")),
    path('', include("addons.urls")),
    path('report/', include("reports.urls")),
    path('blog/', include("blog.urls")),
    path('help-center/', include("help_center.urls")),

    
    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    
    
    # Re-Captcha Validation
    # path('captcha/', include('captcha.urls')),
    
    # Password Reset
    path('user/password-reset/', auth_views.PasswordResetView.as_view( template_name='userauths/password-reset/password_reset.html', subject_template_name='userauths/password-reset/password_reset_subject.txt', email_template_name='userauths/password-reset/password_reset_email.html', success_url='/user/check_email/' ), name='password_reset'),
    path('user/password-reset/done/', auth_views.PasswordResetDoneView.as_view( template_name='userauths/password-reset/password_reset_done.html' ), name='password_reset_done'),
    path('user/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( template_name='userauths/password-reset/password_reset_confirm.html' ), name='password_reset_confirm'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),

    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),),
    
     path("sitemap.xml", sitemap, {"sitemaps": {"blog": GenericSitemap(blog_info_dict), "store": GenericSitemap(store_info_dict)}}),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +[path('404/', pageNotFoundView, name="404"),] + [path('', include("store.urls"))] + [path('<path:invalid_path>/', pageNotFoundView),]
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +[path('404/', pageNotFoundView, name="404"),] + [path('', include("store.urls"))] + [path('<path:invalid_path>/', pageNotFoundView),]
    

userauths/urls.py
from django.urls import path
from userauths import views
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500


app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.Register, name="sign-up"),
    path("sign-in/", views.loginViewTemp, name="sign-in"),
    path("sign-in-2/", views.loginView, name="sign-in-2"),
    path("sign-out/", views.logoutView, name="sign-out"),
    path("vendor_sign_in/", views.loginAsVendor, name="vendor_sign_in"),
    path("check_email/", views.check_email, name="check_email"),
    
    
]

templates/buyer/address-edit.html
{% extends "partials/base-tk.html" %}
{% load static %} 
{% block title %}
  Modifier l'Adresse
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
<!-- {% crispy form %} -->
<section class="oufr-log-rfeg bgcf-f5">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-xl-12 col-xxl-12 m-auto">
        <div class="log_reg_form mt70-992">
          <h2 class="title">Mise à jour de l'Adresse</h2>
          <div class="login_form">
            <form method="POST">
              {% csrf_token %}
              <div class="mb-2 mr-sm-2">{{form.as_p}}</div>

              <button type="submit" class="btn purple-btn btn-thm">Enregistrer la Mise à Jour</button>
              <a href="{% url 'core:buyer-address' %}" class="btn btn-secondary">Retour</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/buyer/buyer-cancel-order.html
{% extends "partials/base-tk.html" %} {% load static %} 
{% block title %}
  Annuler la Commande
{% endblock title %}
{% load crispy_forms_tags %} {% block content %}
<section class="our-dashbord dashbord" style="margin-top: 0">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-xl-12">
        <div class="row">
          <div class="col-xl-12">
            <div class="account_user_deails pl40 pl0-md">
              <div class="ui_kit_tab style2">
                <div class="tab-content pt20 row" id="myTabContent">
                  <div
                    class="tab-pane fade show active col-lg-12"
                          id="t20"
                                role="tabpanel"
aria-labelledby="t20-tab"
                  >
                    <div class="account_user_deails pl40 pl0-lg">
                      <h2 class="title mb30 text-danger">
                        Annuler la Commande #{{ order.oid }}
                      </h2>
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light">
                            <tr>
                              <th scope="col">Produit</th>
                              <th scope="col">Date</th>
                              <th scope="col">Paiement</th>
                              <th scope="col">Statut de Livraison</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for o in orderitems %}
                            <tr>
                              <th scope="row">
                                <a
                                  href="{% url 'store:product-detail' o.product_obj.pid %}"
                                  class="dashed-custom"
                                  >{{o.product_obj.title|truncatechars:27}}</a
                                >
                              </th>
                              <td><small>{{o.date}}</small></td>

                              {% if o.paid == True %}
                              <td class="text-success">Payé</td>
                              {% else %}
                              <td class="text-success">Non Payé</td>
                              {% endif %}

                              <td class="status">
                                <span class="stylde4"
                                  >{{o.delivery_status|title}}</span
                                >
                              </td>
                              <td>{{ cs }}{{ o.total }}</td>

                              {% if o.cancelled == True %}
                              <td class="status">
                                <a class="btn btn-success disabled"
                                  >Commande Annulée</a
                                >
                              </td>
                              {% else %}
                              <td class="status">
                                <a
                                  data-order-item="{{o.id}}"
                                  id="cancel-order"
                                  class="btn btn-danger orderitem{{o.id}}"
                                  >Annuler</a
                                >
                              </td>
                              {% endif %}
                            </tr>
                            {% empty %}
                            <tr>
                              <td><h4>Aucune Commande Encore</h4></td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <div
                    class="tab-pane fade col-lg-12"
                    id="baby"
                    role="tabpanel"
                    aria-labelledby="baby-tab"
                  >
                    <div class="account_user_deails pl40 pl0-lg">
                      <h2 class="title mb30">Expédié</h2>
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light">
                            <tr>
                              <th scope="col">ID</th>
                              <th scope="col">Date</th>
                              <th scope="col">Paiement</th>
                              <th scope="col">Statut de Livraison</th>
                              <th scope="col">Statut de Commande</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for o in shipped %}
                            <tr>
                              <th scope="row">{{o.oid}}</th>
                              <td><small>{{o.date}}</small></td>
                              <td class="text-success">
                                {{o.payment_status|title}}
                              </td>
                              <td class="status">
                                <span class="stylde4"
                                  >{{o.delivery_status|title}}</span
                                >
                              </td>
                              <td class="status">
                                <span class="stdyle4"
                                  >{{o.order_status|title}}</span
                                >
                              </td>
                              <td>{{ cs }}{{ o.total }}</td>
                              <td class="status">
                                <span class="style4"
                                  ><a
                                    href="{% url 'core:buyer-order-detail' o.oid %}"
                                    >Voir Détail</a
                                  ></span
                                >
                              </td>
                            </tr>
                            {% empty %}
                            <tr>
                              <td><h4>Aucune Commande Encore</h4></td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <div
                    class="tab-pane fade col-xl-12"
                    id="furniture"
                    role="tabpanel"
                    aria-labelledby="furniture-tab"
                  >
                    <div class="account_user_deails pl40 pl0-lg">
                      <h2 class="title mb30">Commandes Livrées</h2>
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light">
                            <tr>
                              <th scope="col">ID</th>
                              <th scope="col">Date</th>
                              <th scope="col">Paiement</th>
                              <th scope="col">Statut de Livraison</th>
                              <th scope="col">Statut de Commande</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for o in collected %}
                            <tr>
                              <th scope="row">{{o.oid}}</th>
                              <td><small>{{o.date}}</small></td>
                              <td class="text-success">
                                {{o.payment_status|title}}
                              </td>
                              <td class="status">
                                <span class="stylde4"
                                  >{{o.delivery_status|title}}</span
                                >
                              </td>
                              <td class="status">
                                <span class="stdyle4"
                                  >{{o.order_status|title}}</span
                                >
                              </td>
                              <td>{{ cs }}{{ o.total }}</td>
                              <td class="status">
                                <span class="style4"
                                  ><a
                                    href="{% url 'core:buyer-order-detail' o.oid %}"
                                    >Voir Détail</a
                                  ></span
                                >
                              </td>
                            </tr>
                            {% empty %}
                            <tr>
                              <td><h4>Aucune Commande Encore</h4></td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- nav tab contents End -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/buyer/invoices.html
{% extends "partials/base-tk.html" %}
{% load static %}
{% block title %}
  Factures
{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<section class="our-dashbord dashbord">
  <div class="container">
    <div class="row">
      {% include 'buyer/nav-desktop.html' %}
      <div class="col-lg-9 col-xl-9">
        {% include 'buyer/nav-mobile.html' %}
        <div class="row">
          <div class="col-xl-12">
            <div class="account_user_deails pl40 pl0-md">
              <h2 class="title mb30">Mes Factures</h2>
              <div class="ui_kit_tab style2">
                <!-- Liste de navigation des onglets -->
                <div class="tab-content pt20 row" id="myTabContent">
                  <div class="tab-pane fade show active col-lg-12" id="t20" role="tabpanel" aria-labelledby="t20-tab">
                    <div class="account_user_deails pl40 pl0-lg">
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light" id="">
                            <tr>
                              <th scope="col">ID</th>
                              <!-- <th scope="col">Produit</th> -->
                              <th scope="col">Date</th>
                              <th scope="col">Paiement</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for i in invoices %}
                            <tr>
                              <th scope="row">{{i.oid}}</th>
                              <!-- <td>{{o.product}}</td> -->
                              <td><small>{{i.date}}</small></td>
                              <td class="text-success">{{i.payment_status|title}}</td>
                              <td>{{ cs }}{{ i.total }}</td>
                              <td class="statufs"><span class="style4"><a
                                    href="{% url 'core:buyer-invoice-detail' i.oid %}"><i class="fas fa-eye">
                                    </i></a></span></td>
                            </tr>
                            {% empty %}
                            <tr>
                              <td>
                                <h4>Aucune commande pour le moment</h4>
                              </td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <div class="tab-pane fade col-lg-12" id="baby" role="tabpanel" aria-labelledby="baby-tab">
                    <div class="account_user_deails pl40 pl0-lg">
                      <h2 class="title mb30">Expédié</h2>
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light">
                            <tr>
                              <th scope="col">ID</th>
                              <!-- <th scope="col">Produit</th> -->
                              <th scope="col">Date</th>
                              <th scope="col">Paiement</th>
                              <th scope="col">Statut de livraison</th>
                              <th scope="col">Statut de commande</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for o in shipped %}
                            <tr>
                              <th scope="row">{{o.oid}}</th>
                              <!-- <td>{{o.product}}</td> -->
                              <td><small>{{o.date}}</small></td>
                              <td class="text-success">{{o.payment_status|title}}</td>
                              <td class="status"><span class="stylde4">{{o.delivery_status|title}}</span></td>
                              <td class="status"><span class="stdyle4">{{o.order_status|title}}</span></td>
                              <td>{{ cs }}{{ o.total }}</td>
                              <td class="status"><span class="style4"><a
                                    href="{% url 'core:buyer-order-detail' o.oid %}">Voir les détails</a></span></td>
                            </tr>
                            {% empty %}
                            <tr>
                              <td>
                                <h4>Aucune commande pour le moment</h4>
                              </td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <div class="tab-pane fade col-xl-12" id="furniture" role="tabpanel" aria-labelledby="furniture-tab">
                    <div class="account_user_deails pl40 pl0-lg">
                      <h2 class="title mb30">Commandes Livrées</h2>
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light">
                            <tr>
                              <th scope="col">ID</th>
                              <!-- <th scope="col">Produit</th> -->
                              <th scope="col">Date</th>
                              <th scope="col">Paiement</th>
                              <th scope="col">Statut de livraison</th>
                              <th scope="col">Statut de commande</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for o in collected %}
                            <tr>
                              <th scope="row">{{o.oid}}</th>
                              <!-- <td>{{o.product}}</td> -->
                              <td><small>{{o.date}}</small></td>
                              <td class="text-success">{{o.payment_status|title}}</td>
                              <td class="status"><span class="stylde4">{{o.delivery_status|title}}</span></td>
                              <td class="status"><span class="stdyle4">{{o.order_status|title}}</span></td>
                              <td>{{ cs }}{{ o.total }}</td>
                              <td class="status"><span class="style4"><a
                                    href="{% url 'core:buyer-order-detail' o.oid %}">Voir les détails</a></span></td>
                            </tr>
                            {% empty %}
                            <tr>
                              <td>
                                <h4>Aucune commande pour le moment</h4>
                              </td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>

                  </div>
                </div>
                <!-- Contenu des onglets de navigation -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/buyer/nav-mobile.html
<style>
   ul,li{
      list-style: none;
   }
   .gz-coins {
      /* background: #0c0c0c; */
      width: fit-content;
      /* padding: 0 1rem; */
      border-radius: 3px;
  }
    .gz-coins > span {
      -webkit-text-fill-color: transparent;
      background: linear-gradient(to right top, #1555b5, #008de9, #00bdda, #00e58f, #a2ff00);
      background-image: linear-gradient(to right top, #1555b5, #008de9, #00bdda, #00e58f, #a2ff00);
      background-clip: text;
      -webkit-background-clip: text;
      font-weight: 700;
      font-size: 15px;
      width: fit-content;
  }
</style>
<div class="row" style="margin-top: 140px;">
   <!-- style="margin-top: 100px;" -->
    <div class="col-lg-12">
      
       <div class="dashboard_navigationbar dn db-md " style="margin-top: -100px;">
         <div class="account_details_user d-flex pb10 bb1 mb10 shadow p-3" style="border-radius: 10px;">
            <img class="me-3" src="{{request.user.profile.image.url}}" style="width: 50px; height: 50px; border-radius: 50%; object-fit: cover;" alt="Image générique">
            <div class="content_details text-start">
               
               {% if request.user.profile.full_name %}
               <h5 class="title">{{request.user.profile.full_name|title}}</h5>
               {% else %}
               <h5 class="title">{{request.user.username|title}}</h5>
               {% endif %}
                  
               <a class="stitle" >{{request.user.email}}</a> <br>
               <a class="stitle" >Identifiant du compte: <b><i>{{request.user.id}}</i></b></a>
               <div class="gz-coins">
                  <span>{{ request.user.gz_coins }} GZ Coins</span>
                 </div>
            </div>
         </div>
          <div class="dropdown">
             <button onclick="myFunction()" class="dropbtn"><i class="fas fa-bars pr10"></i> Navigation du tableau de bord</button>
             <ul id="myDropdown" class="dropdown-content">
                {% comment %} TABLEAU DE BORD {% endcomment %}
                {% comment %} <li><a class="active" href="{% url 'core:buyer-dashboard' %}"><span class="bi bi-grid-3x3-gap-fill"></span>Dashboard</a></li> {% endcomment %}
                <li><a class="active" href="{% url 'core:profile' %}"><span class="fas fa-user"></span>Détails du compte</a></li>
                <li><a href="{% url 'core:buyer-orders' %}"><span class="fas fa-list"></span>Commande</a></li>
                {% comment %} ENCHÈRES {% endcomment %}
                {% comment %} <li><a href="{% url 'core:buyer_bids' %}"><span class="fas fa-chart-simple"></span>Mes enchères</a></li> {% endcomment %}
                {% comment %} <li><a href="{% url 'core:buyer_offer' %}"><span class="bi bi-shop"></span>Mes offres</a></li> {% endcomment %}
                <li><a href="{% url 'core:buyer_message' %}"><span class="bi bi-chat-right-dots-fill"></span>Message</a></li>
                <li><a href="{% url 'core:buyer-address' %}"><span class="fas fa-location"></span>Adresse</a></li>
                <li><a href="{% url 'core:buyer-wishlist' %}"><span class="fas fa-heart"></span>Liste de souhaits</a></li>
                <li><a href="{% url 'core:buyer-invoices' %}"><span class="fas fa-file-invoice"></span>Factures</a></li>
                <li><a href="{% url 'core:settings' %}"><span class="bi bi-gear-fill"></span>Paramètres</a></li>
                <li><a href="{% url 'userauths:sign-out' %}"><span class="fas fa-right-from-bracket"></span>Déconnexion</a></li>
             </ul>
          </div>
          
       </div>
    </div>
 </div>