blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogList, name="blog-list"),
    path('category/<str:meta_title>/', views.category_detail, name="category_detail"),
    path('<str:meta_title>', views.blogDetail, name="blog-detail"),

]

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    #path("my-dashboard/", views.buyer_account, name="buyer-dashboard"),
    path("profile/", views.buyer_profile, name="profile"),
    path("settings/", views.buyer_profile_settings, name="settings"),
    path("my-orders/", views.buyer_orders, name="buyer-orders"),
    path("my-orders/<oid>/", views.buyer_order_detail, name="buyer-order-detail"),

    # Shipping Address
    path("my-address/", views.buyer_address, name="buyer-address"),
    path("my-address/edit/<id>/", views.buyer_edit_address, name="buyer-edit-address"),
    path("my-address/delete/<id>/", views.buyer_delete_address, name="buyer-delete-address"),

    # Billing Address
    path("my-billing-address/", views.buyer_billing_address, name="buyer-billing-address"),
    path("my-billing-address/edit/<id>/", views.buyer_edit_billing_address, name="buyer-edit-billing-address"),
    path("add_billing_address", views.add_billing_address, name="add_billing_address"),
    path("my-billing-address/delete/<id>/", views.buyer_delete_billing_address, name="buyer_delete_billing_address"),

    path("my-wishlist/", views.buyer_wishlist, name="buyer-wishlist"),
    path("my-invoices/", views.buyer_invoices, name="buyer-invoices"),
    path("my-invoice/<oid>/", views.buyer_invoice_detail, name="buyer-invoice-detail"),
    path("my-bids/", views.buyer_bids, name="buyer_bids"),
    path("my-bids-detail/<pid>/<bid>", views.buyer_bids_detail, name="buyer_bids_detail"),
    path("order-tracker/", views.buyer_track_order, name="order-tracker"),
    path("tracked-order/<oid>/", views.tracked_order, name="tracked-order"),
    path("buyer_offer", views.buyer_offer, name="buyer_offer"),
    path("buyer_offer_detail/<pid>/<oid>/", views.buyer_offer_detail, name="buyer_offer_detail"),
    path("cancel_order/<oid>/", views.cancel_order, name="cancel_order"),
    path("cancel_orderitem/", views.cancel_orderitem, name="cancel_orderitem"),

    # Messaging
    path('inbox/', views.inbox, name="buyer_message"),
    path('inbox/<username>/', views.get_inbox, name="inbox-detail"),
    path('send_message_ajax/<username>/', views.send_message_ajax, name="send_message_ajax"),
    path('search_user/', views.search_users, name="search_users"),

    # Ajax
    path("delete-wishlist/<id>/", views.delete_from_wishlist, name="delete-wishlist"),
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),
    path("make-default-address/", views.make_address_default, name="make-default-address"),
    path("make-billing-default-address/", views.make_billing_address_default, name="make-default-billing-address"),

]

store/urls.py
from django.urls import path, include
from store import views

app_name = "store"



urlpatterns = [
    path("", views.index, name="home"),
    path("offer/", views.offer, name="offer"),
    path("category/", views.category_list, name="category"),
    path("shop/", views.shop, name="shop"),
    path("category/<str:meta_title>", views.category_shop, name="category-shop"),
    path("brand/<str:meta_title>", views.brand_shop, name="brand-shop"),
    path("hot_deals/", views.hot_deals, name="hot_deals"),
    path("search/", views.search_list, name="search"),
    path("my-cart/", views.cart_view, name="cart-view"),
    path("category/<cid>/", views.category_detail, name="category_detail"),
    path("shipping_address/", views.shipping_address, name="shipping_address"),
    path("checkout/<oid>/", views.checkout_view, name="checkout"),
    path("custom-checkout/<oid>/", views.custom_checkout_view, name="checkout2"),
    path('checkout/order-detail/<id>/', views.PaymentConfirmation.as_view(), name='order-detail'),
    path('success-payment/', views.PaymentSuccessView, name='success'),
    path('failed-payment/', views.PaymentFailedView, name='failed'),    
    
    path("payment-completed/<oid>/", views.payment_completed_view, name="payment-completed"),


    # Ajax URLs
    path("ajax/add-to-cart/", views.add_to_cart, name="add-to-cart"),
    path("ajax/helpful-review/", views.helpful_review, name="helpful-review"),
    path("ajax/add-review/<int:pid>/", views.add_review, name="add-review"),
    path("ajax/ask-question/", views.ask_question, name="ask-question"),
    path('ajax/update-cart/',views.update_cart,name='update-cart'),
    path('ajax/delete-from-cart/',views.delete_item_from_cart,name='delete-from-cart'),

    # API URLs
    path('api/checkout-session/<id>/', views.create_checkout_session, name='api_checkout_session'),
    path('country_get/', views.country_get, name='country_get'),


    path('webhook/', views.webhook, name='webhook'),



    path('get-subcategories/<str:category_meta_title>', views.get_subcategories, name='get-subcategories'),
    path('nav-search/', views.nav_search, name='nav-search'),
    path("<str:meta_title>/", views.product_detail, name="product-detail"),

]

tokyostore/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from store.views import pageNotFoundView
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from store.models import Product, Brand, Category
from blog.models import Post
from store.views import pageNotFoundView

blog_info_dict = {
    "queryset": Post.objects.all(),
    "date_field": "date",
}

store_info_dict = {
    "queryset": Product.objects.all(),
    "date_field": "date",
}

urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('khalabiza/', admin.site.urls),
    
    path('user/', include("userauths.urls")),
    path('', include("core.urls")),
    path('vendor/', include("vendor.urls")),
    path('', include("addons.urls")),
    path('report/', include("reports.urls")),
    path('blog/', include("blog.urls")),
    path('help-center/', include("help_center.urls")),

    
    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    
    
    # Re-Captcha Validation
    # path('captcha/', include('captcha.urls')),
    
    # Password Reset
    path('user/password-reset/', auth_views.PasswordResetView.as_view( template_name='userauths/password-reset/password_reset.html', subject_template_name='userauths/password-reset/password_reset_subject.txt', email_template_name='userauths/password-reset/password_reset_email.html', success_url='/user/check_email/' ), name='password_reset'),
    path('user/password-reset/done/', auth_views.PasswordResetDoneView.as_view( template_name='userauths/password-reset/password_reset_done.html' ), name='password_reset_done'),
    path('user/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( template_name='userauths/password-reset/password_reset_confirm.html' ), name='password_reset_confirm'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),

    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),),
    
     path("sitemap.xml", sitemap, {"sitemaps": {"blog": GenericSitemap(blog_info_dict), "store": GenericSitemap(store_info_dict)}}),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +[path('404/', pageNotFoundView, name="404"),] + [path('', include("store.urls"))] + [path('<path:invalid_path>/', pageNotFoundView),]
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +[path('404/', pageNotFoundView, name="404"),] + [path('', include("store.urls"))] + [path('<path:invalid_path>/', pageNotFoundView),]
    

store/forms.py
from store.models import Review, CartOrderItem, CartOrder
from core.models import Address, BillingAddress
from django import forms

class ReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Write review"}))

    class Meta:
        model = Review
        fields = ['review', 'rating']


class AddressForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)
    mobile = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)
    state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)
    town_city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)
    zip = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)

    class Meta:
        model = Address
        fields = ['full_name','mobile','email','country' ,'state','town_city','zip','address', 'same_as_billing_address']


class BillingAddressForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)
    mobile = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)
    state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)
    town_city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)
    zip = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':''}), required=True)

    class Meta:
        model = BillingAddress
        fields = ['full_name','mobile','email','country','state','town_city','zip','address']


class CartOrderItemForm(forms.ModelForm):
    tracking_id = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Enter Tracking ID'}))

    class Meta:
        model = CartOrderItem
        fields = ['delivery_couriers', 'tracking_id']


class CheckoutForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Full Name'}), required=True)
    mobile = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Active Mobile Number'}), required=True)
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Valid Email Address'}), required=True)
    state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'State'}), required=True)
    town_city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Town or City'}), required=False)
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Street and Home Address'}), required=True)

    billing_state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Billing State'}), required=False)
    billing_town_city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Billing Town or City'}), required=False)
    billing_address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Billing Street and Home Address'}), required=False)

    shipping_method = forms.ChoiceField(choices=CartOrder.SHIPPING_METHOD_CHOICES, widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Shipping Method'}), required=True)
    payment_method = forms.ChoiceField(choices=CartOrder.PAYMENT_METHOD_CHOICES, widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Payment Method'}), required=True)

    class Meta:
        model = CartOrder
        fields = ['full_name', 'mobile', 'email', 'country', 'state', 'town_city', 'address', 'postal_code', 
                  'billing_state', 'billing_town_city', 'billing_address', 'billing_postal_code', 'billing_country']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(CheckoutForm, self).__init__(*args, **kwargs)

        # Set default country to the first one in the list
        default_country = self.fields['country'].queryset.first()
        self.fields['country'].initial = default_country

        if user:
            self.fields['full_name'].initial = user.profile.full_name
            self.fields['email'].initial = user.email
            self.fields['mobile'].initial = user.profile.phone
            self.fields['country'].initial = default_country
            self.fields['state'].initial = user.profile.state
            self.fields['town_city'].initial = user.profile.city
            self.fields['address'].initial = user.profile.address
            
            # Prefill billing address fields
            self.fields['billing_state'].initial = user.billing_state
            self.fields['billing_town_city'].initial = user.profile.city
            self.fields['billing_address'].initial = user.billing_address
            self.fields['billing_postal_code'].initial = user.profile.postal_code
            self.fields['billing_country'].initial = user.billing_country

templates/store/cart.html
{% extends "partials/base.html" %}
{% load static %}
{% block title %}
    Panier
{% endblock title %}
{% block content %}
{% load crispy_forms_tags %}
<style>
  ul,
  li {
    list-style: none;
  }
  @media screen and (max-width: 1100px) {
    table {
      border: 0;
    }

    table caption {
      font-size: 1.3em;
    }

    table thead {
      display: none;
    }

    table tr {
      border-bottom: 3px solid #ddd;
      margin-bottom: 0.625em;
      display: flex;
      justify-content: space-around;
      align-items: center;
    }

    table td,
    th {
      border-bottom: 1px solid #ddd;
      display: block;
      font-size: 0.8em;
      text-align: right;
    }

    table td::before {
      content: attr(data-label);
      float: left;
      font-weight: bold;
      text-transform: uppercase;
    }

    table td:last-child {
      border-bottom: 0;
    }
    .colors__divs{
      flex-direction: column;
    }
  }
  .colors__divs {
    display: flex;
    align-items: flex-start;
    gap: 1rem;
    padding: 1rem 0;
    justify-content: space-evenly;
  }
  .divs__div.color {
    position: relative;
    overflow: hidden;
    align-items: self-start;
    background-color: transparent;
    border: 2px solid gray;
    border-radius: 8px;
    cursor: pointer;
    display: flex;
    flex-direction: column;
    gap: 4px;
    outline: none;
    width: 100%;
  }
  .shipping_option_container {
    padding: 1rem;
    width: 100%;
  }
  .shipping_option_container p {
    font-size: .8125rem;
    font-weight: 400;
    line-height: 1.1;
    margin: 0;
    padding: 1rem 0 0;
    text-align: left;
    color: gray;
  }
  .divs__div.color.selected {
    border-color: var(--MS-C);
    border-width: 2px;
  }
  .lucide-truck, .lucide-store{
    width: fit-content;
  }
  .shipping_text{
    width: fit-content;
      font-weight: 900;
      font-size: large;
      font-style: italic;
      color: black;
  }
  @media screen and (max-width: 768px){
    table tr {
      border-bottom: 3px solid #ddd;
      margin-bottom: 0.625em;
      display: flex;
      justify-content: space-around;
      flex-direction: column;
      align-items: center;
    }
    .shopping_cart_table .table tbody.table_body tr th, .shopping_cart_table .table tbody.table_body tr td{
      padding: 0;
    }
    
  }
  .purple-btn{
    color: white !important;
  }
</style>
<div class="body_content_wrapper position-relative" id="cartList">
  <!-- Breadcrumb de la page intérieure -->
  <section class="inner_page_breadcrumb" style="margin-top: 10px">
    <div class="container">
      <div class="row">
        <div class="col-xl-6">
          <div class="breadcrumb_content">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{% url 'store:home' %}">Accueil</a>
              </li>
              <li class="breadcrumb-item"><a>Boutique</a></li>
              <li class="breadcrumb-item active" aria-current="page">
                <a>Panier d'achats</a>
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Contenu du panier d'achats -->
  <section class="shop-cart pt30">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-lg-4 m-auto">
          <div class="main-title text-center mb50">
            <h2 class="title">Panier d'achat</h2>
            <!-- <input type="text" name="" id=""> -->
          </div>
        </div>
      </div>
      <div class="row mt15" id="cartList">
        <p class="para">
          You have <span class="cart-list">{{totalcartitems }}</span> items in
          your cart
        </p>

        <div class="col-lg-8 col-xl-9">
          <div class="shopping_cart_table table-responsive">
            <table class="table table-borderless">
              <thead>
                <tr>
                  <th scope="col">PRODUIT</th>
                  <th scope="col">PRIX</th>
                  <th scope="col">QUANTITÉ</th>
                  <th scope="col">TOTAL</th>
                  <th scope="col">MISE À JOUR</th>
                  <th scope="col">SUPPRIMER</th>
                </tr>
              </thead>
              <tbody class="table_body">
                {% for product_id, p in cart_data.items %}
                <tr>
                  <th scope="row">
                    <ul class="cart_list d-block d-xl-flex">
                      <li class="ps-1 ps-sm-4 pe-1 pe-sm-4">
                        <a href="#"
                          ><img
                            src="{{p.image}}"
                            style="
                              width: 100px;
                              height: 80px;
                              object-fit: cover;
                              border-radius: 10px;
                            "
                            alt="cart1.png"
                        /></a>
                      </li>
                      <li class="ms-2 ms-md-3">
                        <a
                          class="cart_title"
                          href="{% url 'store:product-detail' meta_title=p.product_meta_title %}"
                        >
                          <span class="fz16">{{p.title|truncatechars:27}}</span>
                          <br />
                        </a>
                      </li>
                    </ul>
                  </th>
                  <td>{{ cs }}{{p.price}}</td>
                  <input
                    type="hidden"
                    class="product-shipping_amount-{{ product_id }}"
                    value="{{ p.shipping_amount }}"
                  />
                  <input
                    type="hidden"
                    class="product-product_processing_fee-{{ product_id }}"
                    value="{{ p.product_processing_fee }}"
                  />
                  <input
                    type="hidden"
                    class="product-product_tax_fee-{{ product_id }}"
                    value="{{ p.product_tax_fee }}"
                  />

                  <input type="hidden" class="product-product_stock_qty-{{ product_id }}" value="{{ p.product_stock_qty }}" />


                  <td>
                    <div class="cart_btn">
                      <div class="quantity-block">
                        <button
                          class="quantity-arrow-minus inner_page"
                          id="decrease-btn"
                          data-btn="{{product_id}}"
                          data-cart-index="{{ product_id }}"
                        >
                          <span class="fa fa-minus"></span>
                        </button>
                        <input
                          class="quantity-num-{{ product_id }} quantity-num inner_page product-qty-{{ product_id }}"
                          id="qty{{product_id}}"
                          type="number"
                          value="{{p.qty}}"
                        />
                        <button
                          class="quantity-arrow-plus inner_page"
                          id="increase-btn"
                          data-btn="{{product_id}}"
                          data-cart-index="{{ product_id }}"
                        >
                          <span class="fas fa-plus"></span>
                        </button>
                      </div>
                    </div>
                    <!-- <input class="cart_count text-center" placeholder="2" type="number"> -->
                  </td>
                  <td class="">{{ cs }}{% widthratio p.price 1 p.qty %}</td>
                  <td class="action text-center" data-title="Remove">
                    <button
                      style="border: none; background: none"
                      class="text-body update-item"
                      data-item="{{ product_id }}"
                    >
                      <i class="bi bi-arrow-clockwise"></i>
                    </button>
                  </td>
                  <td class="action text-center" data-title="Remove">
                    <button
                      style="border: none; background: none"
                      class="text-body delete-item"
                      data-item="{{ product_id }}"
                    >
                      <i class="bi bi-trash"></i>
                    </button>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td>
                    Votre panier est vide.
                    <a href="{% url 'store:shop' %}">Poursuivre les achats</a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="col-lg-4 col-xl-3">
          <div class="order_sidebar_widget style2">
            <h4 class="title">Totaux du Panier</h4>
            <ul>
              <li class="subtitle">
                <p>
                  Sous-total 
                  <span class="float-end"
                    >{{ cs }}{{cart_total_amount|floatformat:2}}</span
                   <li class="subtitle"><hr /></li>
                  <li class="subtitle totals">
                <p>
                  Total
                  <span class="float-end"
                    >{{cs}}{{total_amount|floatformat:2}}</span
                  >
                </p>
              </li>

              {% if coupon_name %}
              <li><b>{{coupon_name}}</b> Coupon Applied</li>
              {% endif %} {% for item in coupon_name.items %} hi {% endfor %}
            </ul>
          </div>

          <a
            href="{% url 'store:shipping_address' %}"
            class="btn w100 mt-4 purple-btn"
            >Continue</a
          >
        </div>
      </div>
    </div>
  </section>
</div>

<script>
  $(document).on("click", "#increase-btn", function () {
    let id = $(this).attr("data-btn");
    var input_value = $("#qty" + id).val();
    console.log(input_value)
    if (input_value >= 0) {
      input_value++;
      $("#qty" + id).val(input_value);
    }
  });

  $(document).on("click", "#decrease-btn", function () {
    let id = $(this).attr("data-btn");
    var input_value = $("#qty" + id).val();
    console.log(input_value)
    if (input_value >= 0) {
      input_value--;
      $("#qty" + id).val(input_value);
    }

    if (input_value === 0) {
      $("#qty" + id).val(1);
    }
  });

  document.addEventListener("DOMContentLoaded", function() {
    const shippingOptions = document.querySelectorAll('.colors__divs .divs__div');

    shippingOptions.forEach(option => {
        option.addEventListener('click', () => {
            shippingOptions.forEach(opt => {
                opt.classList.remove('selected');
            });
            option.classList.add('selected');

            document.getElementById('selectedColorInput').value = option.classList.contains('pick_up_in_store') ? "0" : "1";

            const selectedShippingMethod = document.getElementById('selectedColorInput').value;
            console.log('Selected Shipping Method:', selectedShippingMethod);

            reloadPrices(selectedShippingMethod);
        });
    });

    document.querySelector('.ship_to_home').click();
});

function reloadPrices(selectedShippingMethod) {
    console.log('Reloading prices for shipping method:', selectedShippingMethod);
}
        
</script>

{% endblock content %}

templates/store/country_get.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Bienvenue à la maison !</h1>
    <h3>Vous visitez depuis :</h3>
    <ul>
        <li>Adresse IP : {{ip}}</li>
        <li>Appareil : {{ device_type}}</li>
        <li>Navigateur : {{browser_type}} {{browser_version}}</li>
        <li>Système d'exploitation : {{os_type}} {{os_version}}</li>
        <li>Ville : {{ location_city }}</li>
        <li>Pays : {{ location_country }}</li>
    </ul>
</body>
</html>

templates/store/vendors.html
<!--{% extends "partials/base-tk.html" %}
{% load static %}

{% block title %}
  Vendors
{% endblock title %}
  
{% block content %}

<style>
  ul,li{
     list-style: none;
  }
</style>
    
    
    <!-- Inner Page Breadcrumb 
    <section class="inner_page_breadcrumb">
      <div class="container">
        <div class="row">
          <div class="col-xl-6">
            <div class="breadcrumb_content">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'store:home' %}">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page"><a href="#">Vendors</a></li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </section>

  	<!-- Main Blog Post Content 
  	<section class="blog_post_container pt30 pb80">
  		<div class="container">
        <div class="row">
          <div class="col-lg-6 m-auto">
            <div class="main-title text-center">
              <h2 class="title">Vendors</h2>
            </div>
            <form action="" class="form-group d-flex" method="GET">
                <input name="q" type="text" class="form-control" placeholder="Search Vendors with Shop Names and Email Address...">
                <button style="border: 1px solid rgba(0, 0, 0, 0.199); background: none; border-radius: 6px;" ><i class="fas fa-search"></i></button>
            </form>
          </div>
        </div>
  			<div class="row mt50">
          
  				<div class="col-lg-12 col-xl-12 pl50 pl15-lg">
                    <div class="row">
                    {% for v in vendors %}
                        <div class="col-md-6 col-xl-3">
                        <div class="vendor_grid">
                        <div class="thumb">
                            <img src="{{v.shop_image.url}}" style="width: 100%; height: 250px; object-fit: cover;" alt="Vendor 1 Image">
                        </div>
                        <div class="details">
                            <h5 class="title">{{v.shop_name}}</h5>
                            <div class="flex-grow-1 mb15">
                            <div class="d-block d-block">
                                <h6 class="sub_title mb0">{{v.rating_count}} seller review(s)</h6> <br>
                                <h6 class="sub_title mt0">{{v.product_count}} Products</h6>
                            </div>
                            </div>
                            <div class="vendor_address mb20">
                            <ul class="mb0">
                                
                                {% if v.show_email_address_in_store == True %}
                                    <li><a href="#">{{v.shop_email}}</a></li>
                                {% endif %}
                                
                                    
                            </ul>
                            </div>
                            <div class="d-flex">
                              <a class="btn btn-whifte bdr_thmd purple-btn ml mr-2 ms-2 me-2 w-75" href="{% url 'vendor:vendor_shop_view_page' v.vid %}">Visit Store</a>
                            <a class="btn btn-success bdr_thmd purpdle-btn mt-3r w-25" href="{% url 'core:inbox-detail' v.user.username %}"><i class="bi bi-chat-right-dots-fill"></i></a>
                            </div>
                        </div>
                        </div>
                        </div>
                    {% endfor %}
                    
                    </div>
                <div class="row">
                <div class="col-lg-12">
                    <div class="mbp_pagination text-center">
                        <ul class="page_navigation">
                            {% if vendors.has_previous %}
                            <li class="page-item">
                            <a class="page-link" href="?page={{vendors.previous_page_number}}" tabindex="-1" aria-disabled="true"> <span class="fas fa-angle-left"></span></a>
                            </li>
                        {% endif %}
                        
                        {% if vendors.has_next %}
                            <li class="page-item">
                            <a class="page-link" href="?page={{vendors.next_page_number}}"><span class="fas fa-angle-right"></span></a>
                            </li>
                        {% endif %}
                        </ul>
                    <p class="mt20 pagination_page_count text-center">{{vendors}} -- {{vendors_count}} properties found</p>
                    </div>
                </div>
                </div>
  				</div>
  			</div>
  		</div>
  	</section>
{% endblock content %}