blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogList, name="blog-list"),
    path('category/<str:meta_title>/', views.category_detail, name="category_detail"),
    path('<str:meta_title>', views.blogDetail, name="blog-detail"),

]

store/urls.py
from django.urls import path, include
from store import views

app_name = "store"



urlpatterns = [
    path("", views.index, name="home"),
    path("offer/", views.offer, name="offer"),
    path("category/", views.category_list, name="category"),
    path("shop/", views.shop, name="shop"),
    path("category/<str:meta_title>", views.category_shop, name="category-shop"),
    path("brand/<str:meta_title>", views.brand_shop, name="brand-shop"),
    path("hot_deals/", views.hot_deals, name="hot_deals"),
    path("search/", views.search_list, name="search"),
    path("my-cart/", views.cart_view, name="cart-view"),
    path("category/<cid>/", views.category_detail, name="category_detail"),
    path("shipping_address/", views.shipping_address, name="shipping_address"),
    path("checkout/<oid>/", views.checkout_view, name="checkout"),
    path("custom-checkout/<oid>/", views.custom_checkout_view, name="checkout2"),
    path('checkout/order-detail/<id>/', views.PaymentConfirmation.as_view(), name='order-detail'),
    path('success-payment/', views.PaymentSuccessView, name='success'),
    path('failed-payment/', views.PaymentFailedView, name='failed'),    
    
    path("payment-completed/<oid>/", views.payment_completed_view, name="payment-completed"),


    # Ajax URLs
    path("ajax/add-to-cart/", views.add_to_cart, name="add-to-cart"),
    path("ajax/helpful-review/", views.helpful_review, name="helpful-review"),
    path("ajax/add-review/<int:pid>/", views.add_review, name="add-review"),
    path("ajax/ask-question/", views.ask_question, name="ask-question"),
    path('ajax/update-cart/',views.update_cart,name='update-cart'),
    path('ajax/delete-from-cart/',views.delete_item_from_cart,name='delete-from-cart'),

    # API URLs
    path('api/checkout-session/<id>/', views.create_checkout_session, name='api_checkout_session'),
    path('country_get/', views.country_get, name='country_get'),


    path('webhook/', views.webhook, name='webhook'),



    path('get-subcategories/<str:category_meta_title>', views.get_subcategories, name='get-subcategories'),
    path('nav-search/', views.nav_search, name='nav-search'),
    path("<str:meta_title>/", views.product_detail, name="product-detail"),

]

tokyostore/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from store.views import pageNotFoundView
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from store.models import Product, Brand, Category
from blog.models import Post
from store.views import pageNotFoundView

blog_info_dict = {
    "queryset": Post.objects.all(),
    "date_field": "date",
}

store_info_dict = {
    "queryset": Product.objects.all(),
    "date_field": "date",
}

urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('khalabiza/', admin.site.urls),
    
    path('user/', include("userauths.urls")),
    path('', include("core.urls")),
    path('vendor/', include("vendor.urls")),
    path('', include("addons.urls")),
    path('report/', include("reports.urls")),
    path('blog/', include("blog.urls")),
    path('help-center/', include("help_center.urls")),

    
    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    
    
    # Re-Captcha Validation
    # path('captcha/', include('captcha.urls')),
    
    # Password Reset
    path('user/password-reset/', auth_views.PasswordResetView.as_view( template_name='userauths/password-reset/password_reset.html', subject_template_name='userauths/password-reset/password_reset_subject.txt', email_template_name='userauths/password-reset/password_reset_email.html', success_url='/user/check_email/' ), name='password_reset'),
    path('user/password-reset/done/', auth_views.PasswordResetDoneView.as_view( template_name='userauths/password-reset/password_reset_done.html' ), name='password_reset_done'),
    path('user/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( template_name='userauths/password-reset/password_reset_confirm.html' ), name='password_reset_confirm'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),

    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),),
    
     path("sitemap.xml", sitemap, {"sitemaps": {"blog": GenericSitemap(blog_info_dict), "store": GenericSitemap(store_info_dict)}}),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +[path('404/', pageNotFoundView, name="404"),] + [path('', include("store.urls"))] + [path('<path:invalid_path>/', pageNotFoundView),]
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +[path('404/', pageNotFoundView, name="404"),] + [path('', include("store.urls"))] + [path('<path:invalid_path>/', pageNotFoundView),]
    

templates/payment/payment_detail.html
{% extends "partials/base-tk.html" %} {% load static %} {% block content %} <section class="inner_page_breadcrumb"> <div class="container"> <div class="row"> <div class="col-xl-6"> <div class="breadcrumb_content"> </div> </div> </div> </div> </section> <!-- Suivi de commande --> <section class="our-order-tracking pt0"> <div class="container"> <div class="row"> <div class="col-lg-6 col-xl-5 offset-xl-1"> <div class="order_tracking_content"> <div class="login_form tracking_page pt100 pt50-lg"> <h2 class="title">Choisissez le mode de paiement</h2> <input type="email" name="email" id="email" value="{{request.user.email}}"> <button id="checkout-button" class="btn btn-track btn-thm w100 mt20">Payer {{ cs }}{{object.total}} maintenant</button> </div> </div> </div> </div> </div> </section> <div class="container mt-4"> </div> <script src="https://js.stripe.com/v3/"></script> <script type="text/javascript">var stripe=Stripe('{{stripe_publishable_key}}');var checkoutButton=document.getElementById('checkout-button');checkoutButton.addEventListener('click',function(){var email=document.getElementById('email').value;if(email.length==0){alert("Veuillez saisir votre adresse e-mail.");return;}fetch("{% url 'store:api_checkout_session' id=order.oid %}",{method:'POST',body:JSON.stringify({email:email})}).then(function(response){return response.json();}).then(function(session){return stripe.redirectToCheckout({sessionId:session.sessionId});}).then(function(result){if(result.error){alert(result.error.message);}}).catch(function(error){console.error('Erreur:',error);});});</script> {% endblock content %}

templates/payment/payment_failed.html
{% extends "partials/base-tk.html" %} {% load static %} {% block content %} <div class="body_content_wrapper position-relative"> <!-- Fil d'Ariane de la Page Intérieure --> <section class="inner_page_breadcrumb"> <div class="container"> <div class="row"> </div> </div> </section> <!-- Contenu du Panier de la Boutique --> <section class="shop-cart pt30"> <div class="container"> <div class="row justify-content-center"> <div class="col-lg-6"> <div class="order_complete_message text-center"> <div class="icon bgc-thm1"><span class="fa fa-triangle-exclamation color-white"></span></div> <h2 class="title">Paiement échoué !</h2> <p class="para">Oops... votre paiement n'a pas pu être effectué, veuillez réessayer plus tard.</p> </div> </div> </div> <div class="row"> <div class="col-xl-8 offset-xl-2"> <div class="shop_order_box mt25"> <div class="order_list_raw text-center"> <ul> <li class="list-inline-item"> <p>Numéro de Commande</p> <h5>{{order.oid}}</h5> </li> <li class="list-inline-item"> <p>Date</p> <h5>{{order.date}}</h5> </li> <li class="list-inline-item"> <p>Total</p> <h5>${{order.total}}</h5> </li> <li class="list-inline-item"> <p>Méthode de Paiement</p> <h5>{{order.payment_method}}</h5> </li> </ul> </div> </div> </div> </div> </div> </section> </div> {% endblock content %}

templates/payment/paypal_payment_success.html
<!-- {% extends "partials/base-tk.html" %} {% load static %} {% block content %}
<div class="body_content_wrapper position-relative">
  <!-- Inner Page Breadcrumb 
  <section class="inner_page_breadcrumb" style="margin-top: 150px">
    <div class="container">
      <div class="row">
        <div class="col-xl-6"></div>
      </div>
    </div>
  </section>

  <!-- Shop Checkouts Content 
  <section class="shop-cart pt30">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="order_complete_message text-center">
            <div class="icon bgc-thm1">
              <span class="fa fa-check color-white"></span>
            </div>
            <h2 class="title">Your Order Is Completed !</h2>
            <p class="para">Thank you. Your order has been received.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xl-8 offset-xl-2">
          <div class="shop_order_box mt25">
            <div class="order_list_raw text-center">
              <ul>
                <li class="list-inline-item">
                  <p>Order Number</p>
                  <h5>{{order.oid}}</h5>
                </li>
                <li class="list-inline-item">
                  <p>Date</p>
                  <h5>{{order.date}}</h5>
                </li>
                <li class="list-inline-item">
                  <p>Total</p>
                  <h5>${{order.total}}</h5>
                </li>
                <li class="list-inline-item">
                  <p>Payment Method</p>
                  <h5>{{order.payment_method}}</h5>
                </li>
              </ul>
            </div>
            <div class="order_details">
              <h4 class="title mb25">Order Details</h4>
              <div class="od_content">
                <ul>
                  <li class="subtitle bb1 mb15">
                    <p>Product <span class="float-end">Subtotal</span></p>
                  </li>
                  {% for p in products %}
                  <li>
                    <p class="product_name_qnt">
                      {{p.product_obj.title|truncatechars:27}}
                      <span class="float-end"
                        >{{ cs }}{{p.price}} * {{ p.qty }} =
                        <b>{{ p.total }}</b></span
                      >
                    </p>
                  </li>
                  {% endfor %}

                  <li class="subtitle bt1 bb1 mb10 mt15 pt10">
                    <p>
                      Sub Total
                      <span class="float-end">{{ cs }}{{ order.price }}</span>
                    </p>
                  </li>
                  <li class="subtitle bb1 mb10">
                    <p>
                      Shipping
                      <span class="float-end free_shipping"
                        >{{cs}}{{order.shipping}}</span
                      >
                    </p>
                  </li>
                  <li class="subtitle bb1 mb10">
                    <p>
                      VAT
                      <span class="float-end totals"
                        >{{ cs }}{{ order.vat }}</span
                      >
                    </p>
                  </li>
                  <li class="subtitle bb1 mb10">
                    <p>
                      Payment Method
                      <span class="float-end fwn_bd_color"
                        >Debit/Credit Card</span
                      >
                    </p>
                  </li>
                  <li class="subtitle">
                    <p>
                      Total
                      <span class="float-end totals"
                        >{{ cs }}{{ order.total }}</span
                      >
                    </p>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock content %} -->